// ============================================================
// PRODUCTION ENVIRONMENT — AUTO-GENERATED by scripts/set-env.js
// DO NOT EDIT MANUALLY. Changes will be overwritten on next build.
// ============================================================
export const environment = {
  production: true,
  apiUrl: 'https://vehicle-rental-csi1.onrender.com/api/v1',
  googleClientId: '344907331936-s3r6nq9vb28brtim1pml4qob36bvoh9h.apps.googleusercontent.com',
};
