/**
 * set-env.js — Pre-build script for production deployments.
 *
 * Reads environment variables from the CI/CD pipeline (e.g. Render, GitHub Actions)
 * and writes them into the Angular environment.prod.ts file before `ng build` runs.
 *
 * Required environment variables:
 *   API_URL            — Full backend URL, e.g. https://your-backend.onrender.com/api/v1
 *   GOOGLE_CLIENT_ID   — From Google Cloud Console OAuth 2.0 credentials
 *
 * Usage (already wired into package.json `build:prod` script):
 *   node scripts/set-env.js
 */

const fs = require('fs');
const path = require('path');

const apiUrl = process.env.API_URL;
const googleClientId = process.env.GOOGLE_CLIENT_ID;

if (!apiUrl) {
  console.error('[set-env] ❌ Missing required environment variable: API_URL');
  process.exit(1);
}
if (!googleClientId) {
  console.error('[set-env] ❌ Missing required environment variable: GOOGLE_CLIENT_ID');
  process.exit(1);
}

const envFileContent = `// ============================================================
// PRODUCTION ENVIRONMENT — AUTO-GENERATED by scripts/set-env.js
// DO NOT EDIT MANUALLY. Changes will be overwritten on next build.
// ============================================================
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  googleClientId: '${googleClientId}',
};
`;

const targetPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(targetPath, envFileContent, { encoding: 'utf-8' });

console.log(`[set-env] ✅ environment.prod.ts written successfully.`);
console.log(`[set-env]    apiUrl: ${apiUrl}`);
console.log(`[set-env]    googleClientId: ${googleClientId.slice(0, 20)}...`);
